site_name: CCALL Softphone
site_description:  Hướng dẫn sử dụng CCALL Softphone
theme: readthedocs
pages:
    - 'Hướng dẫn sử dụng CCALL Softphone': 'huong-dan-su-dung-ccall-softphone.md'
    - 'Sách mềm': 'sachmem.md'
